package me.qbosst.bossbot.util

import dev.kord.common.Color as Colour

val Colour.Companion.INDIAN_RED get() =  Colour(0xCD5C5C)
val Colour.Companion.LIGHT_CORAL get() =  Colour(0xF08080)
val Colour.Companion.SALMON get() =  Colour(0xFA8072)
val Colour.Companion.DARK_SALMON get() =  Colour(0xE9967A)
val Colour.Companion.CRIMSON get() =  Colour(0xDC143C)
val Colour.Companion.RED get() =  Colour(0xFF0000)
val Colour.Companion.FIRE_BRICK get() =  Colour(0xB22222)
val Colour.Companion.DARK_RED get() =  Colour(0x8B0000)

// pink colours
val Colour.Companion.PINK get() =  Colour(0xFFC0CB)
val Colour.Companion.LIGHT_PINK get() =  Colour(0xFFB6C1)
val Colour.Companion.HOT_PINK get() =  Colour(0xFF69B4)
val Colour.Companion.DEEP_PINK get() =  Colour(0xFF1493)
val Colour.Companion.MEDIUM_VIOLET_RED get() =  Colour(0xC71585)
val Colour.Companion.PALE_VIOLET_RED get() =  Colour(0xDB7093)

// orange colours
val Colour.Companion.CORAL get() =  Colour(0xFF7F50)
val Colour.Companion.TOMATO get() =  Colour(0xFF6347)
val Colour.Companion.ORANGE_RED get() =  Colour(0xFF4500)
val Colour.Companion.DARK_ORANGE get() =  Colour(0xFF8C00)
val Colour.Companion.ORANGE get() =  Colour(0xFFA500)

// yellow colours
val Colour.Companion.GOLD get() =  Colour(0xFFD700)
val Colour.Companion.YELLOW get() =  Colour(0xFFFF00)
val Colour.Companion.LIGHT_YELLOW get() =  Colour(0xFFFFE0)
val Colour.Companion.LEMON_CHIFFON get() =  Colour(0xFFFACD)
val Colour.Companion.LIGHT_GOLDENROD_YELLOW get() =  Colour(0xFAFAD2)
val Colour.Companion.PAPAYA_WHIP get() =  Colour(0xFFEFD5)
val Colour.Companion.MOCCASIN get() =  Colour(0xFFE4B5)
val Colour.Companion.PEACH_PUFF get() =  Colour(0xFFDAB9)
val Colour.Companion.PALE_GOLDENROD get() =  Colour(0xEEE8AA)
val Colour.Companion.KHAKI get() =  Colour(0xF0E68C)
val Colour.Companion.DARK_KHAKI get() =  Colour(0xBDB76B)

// purple colours
val Colour.Companion.LAVENDER get() =  Colour(0xE6E6FA)
val Colour.Companion.THISTLE get() =  Colour(0xD8BFD8)
val Colour.Companion.PLUM get() =  Colour(0xDDA0DD)
val Colour.Companion.VIOLET get() =  Colour(0xEE82EE)
val Colour.Companion.ORCHID get() =  Colour(0xDA70D6)
val Colour.Companion.FUCHSIA get() =  Colour(0xFF00FF)
val Colour.Companion.MAGENTA get() =  Colour(0xFF00FF)
val Colour.Companion.MEDIUM_ORCHID get() =  Colour(0xBA55D3)
val Colour.Companion.MEDIUM_PURPLE get() =  Colour(0x9370DB)
val Colour.Companion.REBECCA_PURPLE get() =  Colour(0x663399)
val Colour.Companion.BLUE_VIOLET get() =  Colour(0x8A2BE2)
val Colour.Companion.DARK_VIOLET get() =  Colour(0x9400D3)
val Colour.Companion.DARK_ORCHID get() =  Colour(0x9932CC)
val Colour.Companion.DARK_MAGENTA get() =  Colour(0x8B008B)
val Colour.Companion.PURPLE get() =  Colour(0x800080)
val Colour.Companion.INDIGO get() =  Colour(0x4B0082)
val Colour.Companion.SLATE_BLUE get() =  Colour(0x6A5ACD)
val Colour.Companion.DARK_SLATE_BLUE get() =  Colour(0x483D8B)

// green colours
val Colour.Companion.GREEN_YELLOW get() =  Colour(0xADFF2F)
val Colour.Companion.CHARTREUSE get() =  Colour(0x7FFF00)
val Colour.Companion.LAWN_GREEN get() =  Colour(0x7CFC00)
val Colour.Companion.LIME get() =  Colour(0x00FF00)
val Colour.Companion.LIME_GREEN get() =  Colour(0x32CD32)
val Colour.Companion.PALE_GREEN get() =  Colour(0x98FB98)
val Colour.Companion.LIGHT_GREEN get() =  Colour(0x90EE90)
val Colour.Companion.MEDIUM_SPRING_GREEN get() =  Colour(0x00FA9A)
val Colour.Companion.SPRING_GREEN get() =  Colour(0x00FF7F)
val Colour.Companion.MEDIUM_SEA_GREEN get() =  Colour(0x3CB371)
val Colour.Companion.SEA_GREEN get() =  Colour(0x2E8B57)
val Colour.Companion.FOREST_GREEN get() =  Colour(0x228B22)
val Colour.Companion.GREEN get() =  Colour(0x008000)
val Colour.Companion.DARK_GREEN get() =  Colour(0x006400)
val Colour.Companion.YELLOW_GREEN get() =  Colour(0x9ACD32)
val Colour.Companion.OLIVE_DRAB get() =  Colour(0x6B8E23)
val Colour.Companion.OLIVE get() =  Colour(0x808000)
val Colour.Companion.DARK_OLIVE_GREEN get() =  Colour(0x556B2F)
val Colour.Companion.MEDIUM_AQUAMARINE get() =  Colour(0x66CDAA)
val Colour.Companion.DARK_SEA_GREEN get() =  Colour(0x8FBC8B)
val Colour.Companion.LIGHT_SEA_GREEN get() =  Colour(0x20B2AA)
val Colour.Companion.DARK_CYAN get() =  Colour(0x008B8B)
val Colour.Companion.TEAL get() =  Colour(0x008080)

// blue colours
val Colour.Companion.AQUA get() =  Colour(0x00FFFF)
val Colour.Companion.CYAN get() =  Colour(0x00FFFF)
val Colour.Companion.LIGHT_CYAN get() =  Colour(0xE0FFFF)
val Colour.Companion.PALE_TURQUOISE get() =  Colour(0xAFEEEE)
val Colour.Companion.AQUAMARINE get() =  Colour(0x7FFFD4)
val Colour.Companion.TURQUOISE get() =  Colour(0x40E0D0)
val Colour.Companion.MEDIUM_TURQUOISE get() =  Colour(0x48D1CC)
val Colour.Companion.DARK_TURQUOISE get() =  Colour(0x00CED1)
val Colour.Companion.CADET_BLUE get() =  Colour(0x5F9EA0)
val Colour.Companion.STEEL_BLUE get() =  Colour(0x4682B4)
val Colour.Companion.LIGHT_STEEL_BLUE get() =  Colour(0xB0C4DE)
val Colour.Companion.POWDER_BLUE get() =  Colour(0xB0E0E6)
val Colour.Companion.LIGHT_BLUE get() =  Colour(0xADD8E6)
val Colour.Companion.SKY_BLUE get() =  Colour(0x87CEEB)
val Colour.Companion.LIGHT_SKY_BLUE get() =  Colour(0x87CEFA)
val Colour.Companion.DEEP_SKY_BLUE get() =  Colour(0x00BFFF)
val Colour.Companion.DODGER_BLUE get() =  Colour(0x1E90FF)
val Colour.Companion.CORNFLOWER_BLUE get() =  Colour(0x6495ED)
val Colour.Companion.MEDIUM_SLATE_BLUE get() =  Colour(0x7B68EE)
val Colour.Companion.ROYAL_BLUE get() =  Colour(0x4169E1)
val Colour.Companion.BLUE get() =  Colour(0x0000FF)
val Colour.Companion.MEDIUM_BLUE get() =  Colour(0x0000CD)
val Colour.Companion.DARK_BLUE get() =  Colour(0x00008B)
val Colour.Companion.NAVY get() =  Colour(0x000080)
val Colour.Companion.MIDNIGHT_BLUE get() =  Colour(0x191970)

// brown colours
val Colour.Companion.CORNSILK get() =  Colour(0xFFF8DC)
val Colour.Companion.BLANCHED_ALMOND get() =  Colour(0xFFEBCD)
val Colour.Companion.BISQUE get() =  Colour(0xFFE4C4)
val Colour.Companion.NAVAJO_WHITE get() =  Colour(0xFFDEAD)
val Colour.Companion.WHEAT get() =  Colour(0xF5DEB3)
val Colour.Companion.BURLY_WOOD get() =  Colour(0xDEB887)
val Colour.Companion.TAN get() =  Colour(0xD2B48C)
val Colour.Companion.ROSY_BROWN get() =  Colour(0xBC8F8F)
val Colour.Companion.SANDY_BROWN get() =  Colour(0xF4A460)
val Colour.Companion.GOLDENROD get() =  Colour(0xDAA520)
val Colour.Companion.DARK_GOLDENROD get() =  Colour(0xB8860B)
val Colour.Companion.PERU get() =  Colour(0xCD853F)
val Colour.Companion.CHOCOLATE get() =  Colour(0xD2691E)
val Colour.Companion.SADDLE_BROWN get() =  Colour(0x8B4513)
val Colour.Companion.SIENNA get() =  Colour(0xA0522D)
val Colour.Companion.BROWN get() =  Colour(0xA52A2A)
val Colour.Companion.MAROON get() =  Colour(0x800000)

// white colours
val Colour.Companion.WHITE get() =  Colour(0xFFFFFF)
val Colour.Companion.SNOW get() =  Colour(0xFFFAFA)
val Colour.Companion.HONEY_DEW get() =  Colour(0xF0FFF0)
val Colour.Companion.MINT_CREAM get() =  Colour(0xF5FFFA)
val Colour.Companion.AZURE get() =  Colour(0xF0FFFF)
val Colour.Companion.ALICE_BLUE get() =  Colour(0xF0F8FF)
val Colour.Companion.GHOST_WHITE get() =  Colour(0xF8F8FF)
val Colour.Companion.WHITE_SMOKE get() =  Colour(0xF5F5F5)
val Colour.Companion.SEA_SHELL get() =  Colour(0xFFF5EE)
val Colour.Companion.BEIGE get() =  Colour(0xF5F5DC)
val Colour.Companion.OLD_LACE get() =  Colour(0xFDF5E6)
val Colour.Companion.FLORAL_WHITE get() =  Colour(0xFFFAF0)
val Colour.Companion.IVORY get() =  Colour(0xFFFFF0)
val Colour.Companion.ANTIQUE_WHITE get() =  Colour(0xFAEBD7)
val Colour.Companion.LINEN get() =  Colour(0xFAF0E6)
val Colour.Companion.LAVENDER_BLUSH get() =  Colour(0xFFF0F5)
val Colour.Companion.MISTY_ROSE get() =  Colour(0xFFE4E1)

// gray colours
val Colour.Companion.GAINSBORO get() =  Colour(0xDCDCDC)
val Colour.Companion.LIGHT_GRAY get() =  Colour(0xD3D3D3)
val Colour.Companion.SILVER get() =  Colour(0xC0C0C0)
val Colour.Companion.DARK_GRAY get() =  Colour(0xA9A9A9)
val Colour.Companion.GRAY get() =  Colour(0x808080)
val Colour.Companion.DIM_GRAY get() =  Colour(0x696969)
val Colour.Companion.LIGHT_SLATE_GRAY get() =  Colour(0x778899)
val Colour.Companion.SLATE_GRAY get() =  Colour(0x708090)
val Colour.Companion.DARK_SLATE_GRAY get() =  Colour(0x2F4F4F)
val Colour.Companion.BLACK get() =  Colour(0x000000)

fun Colour.Companion.random(): Colour = Colour((0x000000..0xffffff).random())
